server=http://localhost:8111
apiVersion=/app/rest
admin.username=admin
admin.password=admin
admin.bearerToken=eyJ0eXAiOiAiVENWMiJ9.LUZtc09BVl9yMHZZT1lDOFpsSE5Kb3pnSkNz.NzNhNzY1MzQtNzQ5YS00ZjE4LWIyOTMtM2Q1ZDQ3ZjJjNjBl
agent.name=docker-agent-01