ALERT_SELECTOR = '[data-test="alert"]'
LOGIN_USERNAME_INPUT = '[data-test="login-username"]'
LOGIN_PASSWORD_INPUT = '[data-test="login-password"]'
LOGIN_BUTTON = '[data-test="login-submit"]'
LOGIN_ERROR_MESSAGE = '[data-test="login-error"]'
ADMIN_PANEL_TEXT = "h1"
ADMIN_CREATE_USER_BUTTON = '[data-test="create-user"]'
ADMIN_USERNAME_INPUT = '[data-test="username-input"]'
ADMIN_PASSWORD_INPUT = '[data-test="password-input"]'
ADMIN_CONFIRM_PASSWORD_INPUT = '[data-test="confirm-password-input"]'
ADMIN_SUBMIT_BUTTON = '[data-test="submit"]'
ADMIN_USERS_LIST = '[data-test="users-list"], table'
PROJECTS_LIST = '[data-test="projects-list"]'
CREATE_PROJECT_BUTTON = '[data-test="create-project"]'
PROJECT_ID_INPUT = '[data-test="project-id-input"]'
PROJECT_NAME_INPUT = '[data-test="project-name-input"]'
PROJECT_SUBMIT_BUTTON = '[data-test="submit"]'
PROJECT_WELCOME_TEXT = "main h1, h1"
PROJECT_NAVIGATION_MENU = '[data-test="sidebar"], nav'
