name: teamcity

services:
  teamcity-server:
    image: ${TEAMCITY_SERVER_IMAGE:-jetbrains/teamcity-server:2025.11.2}
    container_name: teamcity-server
    environment:
      - TEAMCITY_SERVER_OPTS=-Dteamcity.startup.maintenance=false
    ports:
      - "8111:8111"
    volumes:
      - ${TEAMCITY_SERVER_DATADIR}:/data/teamcity_server/datadir
      - ${TEAMCITY_SERVER_LOGS}:/opt/teamcity/logs
    restart: unless-stopped

  teamcity-agent:
    image: ${TEAMCITY_AGENT_IMAGE:-jetbrains/teamcity-agent:2025.11.2}
    container_name: teamcity-agent-01
    depends_on:
      - teamcity-server
    environment:
      SERVER_URL: http://teamcity-server:8111
      AGENT_NAME: docker-agent-01
    volumes:
      - teamcity_agent:/opt/buildagent
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  teamcity_agent:
